/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giaodien.Model;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dungl
 */
public class ChamCong extends javax.swing.JFrame {

    /**
     * Creates new form ChamCong
     */
    public ChamCong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_MaCC = new javax.swing.JTextField();
        txt_MaNV = new javax.swing.JTextField();
        btn_Show = new javax.swing.JButton();
        btn_Fix = new javax.swing.JButton();
        btn_Del = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();
        btn_Out = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        txt_Ngay = new javax.swing.JTextField();
        btn_Find = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Cb_TT = new javax.swing.JComboBox<>();
        txt_GioLam = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Mã chấm công:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 7, -1, 19));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã nhân viên:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 47, -1, 19));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Ngày:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 92, -1, 19));
        getContentPane().add(txt_MaCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 5, 269, -1));
        getContentPane().add(txt_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 45, 264, -1));

        btn_Show.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_Show.setText("Hiển thị");
        btn_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 45, 79, -1));

        btn_Fix.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_Fix.setText("Sửa");
        btn_Fix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FixActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Fix, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 87, 79, -1));

        btn_Del.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_Del.setText("Xóa");
        btn_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Del, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 129, 79, -1));

        btn_Add.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_Add.setText("Thêm");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 45, 79, -1));

        btn_Out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/Exit.png"))); // NOI18N
        btn_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 5, -1, -1));

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã chấm công", "Mã nhân viên", "Ngày", "Trạng thái", "Giờ làm"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 232, 710, 360));

        txt_Ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NgayActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Ngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 87, 264, -1));

        btn_Find.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_Find.setText("Tìm kiếm");
        btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FindActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 87, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Trạng thái");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 131, -1, 19));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Giờ làm:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 171, -1, 21));

        Cb_TT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cb_TT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đủ công", "Thiếu công", " " }));
        Cb_TT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cb_TTItemStateChanged(evt);
            }
        });
        getContentPane().add(Cb_TT, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 129, 113, -1));

        txt_GioLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GioLamActionPerformed(evt);
            }
        });
        getContentPane().add(txt_GioLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 171, 264, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowActionPerformed

               try {

            Connection kn=ketnoi.KNCSDL();

            String sql1="select * from chamcong";

            Statement stm=kn.createStatement();

            ResultSet rs= stm.executeQuery(sql1);
            DefaultTableModel dtm=(DefaultTableModel)tb.getModel();
            dtm.setRowCount(0);

            while (rs.next())
            {
            Object objliss[]={
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5)
            };
            dtm.addRow(objliss);
            tb.setModel(dtm);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChamCong.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_ShowActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        int row= tb.getSelectedRow();

        String macc=tb.getValueAt(row, 0).toString();
        String manv=tb.getValueAt(row, 1).toString();
        String ngay=tb.getValueAt(row, 2).toString();
        String tt=tb.getValueAt(row, 3).toString();
        String gio=tb.getValueAt(row, 4).toString();
        
        txt_MaCC.setText(macc);
        txt_MaNV.setText(manv);
        txt_Ngay.setText(ngay);
        Cb_TT.setSelectedItem(tt);
        txt_GioLam.setText(gio);
 
    }//GEN-LAST:event_tbMouseClicked

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        String macc= txt_MaCC.getText();
        String manv= txt_MaNV.getText();
        String ngay= txt_Ngay.getText();
        String tt = Cb_TT.getSelectedItem().toString();
        String gio= txt_GioLam.getText();


        try {

            Connection kn= ketnoi.KNCSDL(); 

            String sqlthem= "insert into chamcong values ('"+macc+"','"+manv+"','"+ngay+"','"+tt +"','"+gio+"')";

            Statement stm = kn.createStatement();

            stm.executeUpdate(sqlthem);

            String sql1="select * from chamcong";

            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm= (DefaultTableModel) tb.getModel();
            dtm.setRowCount(0);

            while (rs.next())
            {
                Object objliss[] = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                    
                };
                dtm.addRow(objliss);
                tb.setModel(dtm);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ChamCong.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_FixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FixActionPerformed
        String macc= txt_MaCC.getText();
        String manv= txt_MaNV.getText();
        String ngay= txt_Ngay.getText();
        String tt = Cb_TT.getSelectedItem().toString();
        String gio= txt_GioLam.getText();


        try {
        Connection kn = ketnoi.KNCSDL();
        String gioLamValue = (gio != null) ? "'" + gio + "'" : "NULL";
        String sqlsua = "UPDATE chamcong SET MaNhanVien = '" + manv + "', Ngay = '" + ngay + "', TrangThai = '" + tt + "', GioLam = '" + gio + "' WHERE MaChamCong = '" + macc + "'";

        Statement stm = kn.createStatement();

        int affectedRows = stm.executeUpdate(sqlsua);
        
        if (affectedRows > 0) {

            String sql1 = "SELECT * FROM chamcong";
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm = (DefaultTableModel) tb.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {
                Object objliss[] = {
                    rs.getString(1), 
                    rs.getString(2), 
                    rs.getString(3),
                    rs.getString(4), 
                    rs.getString(5)  
                };
                dtm.addRow(objliss);
            }
            tb.setModel(dtm);
        } else {

            System.out.println("Không tìm thấy bản ghi nào để sửa");
        }
        }
        catch (SQLException ex) {
            Logger.getLogger(ChamCong.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_FixActionPerformed

    private void btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FindActionPerformed
    String tuKhoa = txt_MaCC.getText().trim();
    

    if (tuKhoa.isEmpty()) {

        return;
    }


    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{"Mã chấm công", "Mã nhân viên", "Ngày", "Trạng thái","Giờ làm"});
    

    DefaultTableModel currentModel = (DefaultTableModel) tb.getModel();
    for (int i = 0; i < currentModel.getRowCount(); i++) {

        String tenTrongBang = currentModel.getValueAt(i, 0).toString();

        if (tenTrongBang.equalsIgnoreCase(tuKhoa)) {
            model.addRow(new Object[]{
                currentModel.getValueAt(i, 0),
                currentModel.getValueAt(i, 1),
                currentModel.getValueAt(i, 2),
                currentModel.getValueAt(i, 3),
                currentModel.getValueAt(i, 4)
                
            });
        }
    }
    
    // Hiển thị kết quả tìm kiếm trên bảng tb
    tb.setModel(model);  
    
    }//GEN-LAST:event_btn_FindActionPerformed

    private void btn_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelActionPerformed
        String macanxoa = txt_MaCC.getText();
        try {
            Connection kn = ketnoi.KNCSDL();
            String sqlxoa= "delete from chamcong where MaChamCong='"+macanxoa+"'";
            Statement stm = kn.createStatement();
            stm.executeUpdate(sqlxoa);
            int row= tb.getSelectedRow();
            DefaultTableModel dtm = (DefaultTableModel) tb.getModel();
            dtm.removeRow(row);
            
        
        } catch (SQLException ex) {
            Logger.getLogger(ChamCong.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_DelActionPerformed

    private void btn_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chăn muốn thoát chứ", "Thoát",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            dispose();
        }
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btn_OutActionPerformed

    private void txt_NgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NgayActionPerformed

    private void txt_GioLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GioLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GioLamActionPerformed

    private void Cb_TTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cb_TTItemStateChanged
    String selectedValue = (String) Cb_TT.getSelectedItem(); // Lấy giá trị được chọn từ JComboBox

    // Kiểm tra nếu giá trị được chọn là "Đủ công", thiết lập giá trị của txt_GioLam thành "8"
    if (selectedValue.equals("Đủ công")) 
    {
        txt_GioLam.setText("8");
    } 
        else 
        {
        txt_GioLam.setText("");
        }
    }//GEN-LAST:event_Cb_TTItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChamCong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb_TT;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Del;
    private javax.swing.JButton btn_Find;
    private javax.swing.JButton btn_Fix;
    private javax.swing.JButton btn_Out;
    private javax.swing.JButton btn_Show;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txt_GioLam;
    private javax.swing.JTextField txt_MaCC;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_Ngay;
    // End of variables declaration//GEN-END:variables
}
