/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giaodien.Model;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class Hopdong extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Hopdong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_hd = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nkt = new javax.swing.JTextField();
        txt_loaihd = new javax.swing.JTextField();
        txt_mahd = new javax.swing.JTextField();
        txt_manv = new javax.swing.JTextField();
        btn_sua = new javax.swing.JButton();
        btn_find = new javax.swing.JButton();
        btn_hienthi = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nbd = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_hd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hợp đồng", "Mã nhân viên", "Loại hợp đồng", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ));
        tb_hd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_hdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_hd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 590));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Loại hợp đồng");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Mã nhân viên");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Mã hợp đồng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));
        getContentPane().add(txt_nkt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 280, -1));
        getContentPane().add(txt_loaihd, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 280, -1));
        getContentPane().add(txt_mahd, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 280, -1));
        getContentPane().add(txt_manv, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 280, -1));

        btn_sua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, -1, -1));

        btn_find.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_find.setText("Tìm kiếm");
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });
        getContentPane().add(btn_find, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, -1, -1));

        btn_hienthi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_hienthi.setText("Hiển thị");
        btn_hienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hienthiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hienthi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 270, -1, -1));

        btn_them.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        getContentPane().add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, -1, -1));

        btn_xoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_xoa.setText("Xoá");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, -1, -1));

        btn_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/Exit.png"))); // NOI18N
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        getContentPane().add(btn_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 30, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Ngày bắt đầu");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Ngày kết thúc");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));
        getContentPane().add(txt_nbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 280, -1));

        jTextField6.setText("jTextField1");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngtree-collaborative-network-connecting-employees-and-community-for-responsibility-sharing-and-information-exchange-photo-image_40550292.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 820, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
         String mahd = txt_mahd.getText();
        String manv = txt_manv.getText();
        String loaihd = txt_loaihd.getText();
        String nbd = txt_nbd.getText();
        String nkt = txt_nkt.getText();
        try {
            Connection kn = ketnoi.KNCSDL();
            String sqlsua = "Update hopdong set MaNhanVien='"+manv+"',LoaiHopDong = '"+loaihd+"',NgayBatDau='"+nbd+"',NgayKetThuc='"+nkt+"' where MaHopDong = '"+mahd+"'";
             Statement stm = kn.createStatement();
            stm.executeUpdate(sqlsua);
            String sql1="Select * from hopdong";
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm = (DefaultTableModel) tb_hd.getModel();
            dtm.setRowCount(0)
                    ;
            
            while(rs.next()){
                Object objliss[]={
                  rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                      
                }; dtm.addRow(objliss);
            }
            tb_hd.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(Hopdong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn thoát chứ","thoát",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            dispose();
        }
        
        new Dashboard().setVisible(true);
        
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_hienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hienthiActionPerformed
        try {
            // TODO add your handling code here:
            Connection kn = ketnoi.KNCSDL();
            String sql1="Select * from hopdong";
            Statement stm = kn.createStatement();
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm = (DefaultTableModel) tb_hd.getModel();
            dtm.setRowCount(0);
            while(rs.next()){
                Object objliss[]={
                  rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                }; dtm.addRow(objliss);
                
            }
            tb_hd.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(Hopdong.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_hienthiActionPerformed

    private void tb_hdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_hdMouseClicked
        // TODO add your handling code here:
        int row = tb_hd.getSelectedRow();
        String mahd = tb_hd.getValueAt(row, 0).toString();
         String manv = tb_hd.getValueAt(row, 1).toString();
          String loaihd = tb_hd.getValueAt(row, 2).toString();
           String nbd = tb_hd.getValueAt(row, 3).toString();
            String nkt = tb_hd.getValueAt(row, 4).toString();
            
            txt_mahd.setText(mahd);
            txt_manv.setText(manv);
            txt_loaihd.setText(loaihd);
            txt_nbd.setText(nbd);
            txt_nkt.setText(nkt);
    }//GEN-LAST:event_tb_hdMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String mahd = txt_mahd.getText();
        String manv = txt_manv.getText();
        String loaihd = txt_loaihd.getText();
        String nbd = txt_nbd.getText();
        String nkt = txt_nkt.getText();
        
        try {
            Connection kn = ketnoi.KNCSDL();
            String sqlthem="Insert into hopdong values('"+mahd+"','"+manv+"','"+loaihd+"','"+nbd+"','"+nkt+"')";
            Statement stm = kn.createStatement();
            stm.executeUpdate(sqlthem);
            String sql1="Select * from hopdong";
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm = (DefaultTableModel) tb_hd.getModel();
            dtm.setRowCount(0)
                    ;
            
            while(rs.next()){
                Object objliss[]={
                  rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                      
                }; dtm.addRow(objliss);
            }
            tb_hd.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(Hopdong.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        String mahd = txt_mahd.getText();
        String manv = txt_manv.getText();
        String loaihd = txt_loaihd.getText();
        String nbd = txt_nbd.getText();
        String nkt = txt_nkt.getText();
        
        try {
            Connection kn = ketnoi.KNCSDL();
            String sqlxoa="Delete from hopdong where MaHopDong = '"+mahd+"'";
            Statement stm = kn.createStatement();
            stm.executeUpdate(sqlxoa);
            String sql1="Select * from hopdong";
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm = (DefaultTableModel) tb_hd.getModel();
            dtm.setRowCount(0)
                    ;
            
            while(rs.next()){
                Object objliss[]={
                  rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                      
                }; dtm.addRow(objliss);
            }
            tb_hd.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(Hopdong.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        // TODO add your handling code here:
        String mahd = txt_mahd.getText();
        String manv = txt_manv.getText();
        String loaihd = txt_loaihd.getText();
        String nbd = txt_nbd.getText();
        String nkt = txt_nkt.getText();
        
        try {
            Connection kn = ketnoi.KNCSDL();
            String sqlfind="Select * from hopdong where MaHopDong='"+txt_mahd.getText()+"'";
            Statement stm = kn.createStatement();
            
           
            ResultSet rs = stm.executeQuery(sqlfind);
            DefaultTableModel dtm = (DefaultTableModel) tb_hd.getModel();
            dtm.setRowCount(0)
                    ;
            
            while(rs.next()){
                Object objliss[]={
                  rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                      
                }; dtm.addRow(objliss);
            }
            tb_hd.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(Hopdong.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_findActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hopdong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_hienthi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tb_hd;
    private javax.swing.JTextField txt_loaihd;
    private javax.swing.JTextField txt_mahd;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JTextField txt_nbd;
    private javax.swing.JTextField txt_nkt;
    // End of variables declaration//GEN-END:variables
}
