/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giaodien.Model;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.ImageIcon;
/**


/**
 *
 * @author Admin
 */
public class Phongban extends javax.swing.JFrame {

    /**
     * Creates new form Phongban
     */
    public Phongban() {
        initComponents();
        hienthi();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_phongban = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_timkiem = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        txt_mota = new javax.swing.JTextField();
        txt_mapb = new javax.swing.JTextField();
        txt_tenpb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí phòng ban");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_phongban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã phòng ban", "Tên phòng ban", "Mô tả"
            }
        ));
        tb_phongban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_phongbanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_phongban);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 240, 660, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/Exit.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 0, 34, 33));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Mã phòng ban");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 31, 115, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mô tả");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 145, 115, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Tên phòng ban");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 89, 115, 30));

        btn_timkiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });
        getContentPane().add(btn_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, 40));

        btn_them.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        getContentPane().add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, 40));

        btn_sua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, 40));

        btn_xoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_xoa.setText("Xoá");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 40));
        getContentPane().add(txt_mota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 280, 30));
        getContentPane().add(txt_mapb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 32, 280, 30));
        getContentPane().add(txt_tenpb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 280, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icon_phongban.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn thoát chứ","Thoát",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION)
        {
            dispose();
        }
        
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tb_phongbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_phongbanMouseClicked
        // TODO add your handling code here:
        int row = tb_phongban.getSelectedRow();
        String mapb = tb_phongban.getValueAt(row, 0).toString();
        String tenpb = tb_phongban.getValueAt(row, 1).toString();
        String mota = tb_phongban.getValueAt(row, 2).toString();
        
        txt_mapb.setText(mapb);
         txt_tenpb.setText(tenpb);
         txt_mota.setText(mota);
        
    }//GEN-LAST:event_tb_phongbanMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        String mapb = txt_mapb.getText();
        String tenpb = txt_tenpb.getText();
        String mota = txt_mota.getText();
        try {
            // TODO add your handling code here:
            Connection kn= ketnoi.KNCSDL();
            String sqlthem="Insert into phongban values('"+mapb+"','"+tenpb+"','"+mota+"') ";
            Statement stm=kn.createStatement();
            stm.executeUpdate(sqlthem);
            String sql1="Select * from phongban";
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm =(DefaultTableModel) tb_phongban.getModel();
            dtm.setRowCount(0)
                    ;
            
            while(rs.next()){
                Object objliss[]={
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)
                };dtm.addRow(objliss);
            }
                
            tb_phongban.setModel(dtm);
            
        } catch (SQLException ex) {
            Logger.getLogger(Phongban.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        String mapb = txt_mapb.getText();
        String tenpb = txt_tenpb.getText();
        String mota = txt_mota.getText();
        try {
            // TODO add your handling code here:
            Connection kn = ketnoi.KNCSDL();
            String sqlsua="Update phongban set TenPhongBan='"+tenpb+"',MoTa='"+mota+"' where MaPhongBan='"+mapb+"'";
            Statement stm = kn.createStatement();
            stm.executeUpdate(sqlsua);
            String sql1="Select * from phongban";
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm = (DefaultTableModel) tb_phongban.getModel();
            dtm.setRowCount(0);
            while(rs.next()){
                Object objliss[]={
                  rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)
                };dtm.addRow(objliss);
                
            }
            tb_phongban.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(Phongban.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
       String mapb = txt_mapb.getText();
        String tenpb = txt_tenpb.getText();
        String mota = txt_mota.getText();
        try {
            // TODO add your handling code here:
            Connection kn = ketnoi.KNCSDL();
            String sqlxoa="Delete from phongban where MaPhongBan ='"+mapb+"'";
            Statement stm = kn.createStatement();
            stm.executeUpdate(sqlxoa);
            String sql1="Select * from phongban ";
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm = (DefaultTableModel) tb_phongban.getModel();
            dtm.setRowCount(0)
                    ;
            while(rs.next()){
                Object objliss[]={
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)
                };
                dtm.addRow(objliss);
            }
            tb_phongban.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(Phongban.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String mapb = txt_mapb.getText();
        String tenpb = txt_tenpb.getText();
        String mota = txt_mota.getText();
        
        try {
            Connection kn=ketnoi.KNCSDL();
          String sqlfind="Select * from nhanvien where MaNhanVien = '"+txt_mapb.getText()+"'";
            Statement stm = kn.createStatement();
             ResultSet rs= stm.executeQuery(sqlfind);
            DefaultTableModel dtm = (DefaultTableModel) tb_phongban.getModel();
            dtm.setRowCount(0);
             while(rs.next()){
                Object objliss[]={
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)
                };
                dtm.addRow(objliss);
            }
            tb_phongban.setModel(dtm);
            
        } catch (SQLException ex) {
            Logger.getLogger(Phongban.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btn_timkiemActionPerformed

    public void hienthi(){
        try {
            Connection kn = ketnoi.KNCSDL();
            String sql1="Select * from phongban";
            Statement stm = kn.createStatement();
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm = (DefaultTableModel) tb_phongban.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
                Object objliss[]={
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)
                };
                dtm.addRow(objliss);
                tb_phongban.setModel(dtm);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Phongban.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phongban().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_phongban;
    private javax.swing.JTextField txt_mapb;
    private javax.swing.JTextField txt_mota;
    private javax.swing.JTextField txt_tenpb;
    // End of variables declaration//GEN-END:variables
}
