/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giaodien.Model;

import Giaodien.Model.ChamCong;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;

/**
 *
 * @author dungl
 */
public class TinhLuong extends javax.swing.JFrame {

    /**
     * Creates new form TinhLuong
     */
    public TinhLuong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_MaBL = new javax.swing.JTextField();
        txt_MaNV = new javax.swing.JTextField();
        btn_Show = new javax.swing.JButton();
        btn_Del = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();
        btn_Out = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btn_Find = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_SoCong = new javax.swing.JTextField();
        txt_GioThieuCong = new javax.swing.JTextField();
        btn_Sua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Bảng tính lương nhân viên");

        jLabel2.setText("Mã bảng lương:");

        jLabel3.setText("Mã nhân viên:");

        btn_Show.setText("Hiển thị");
        btn_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowActionPerformed(evt);
            }
        });

        btn_Del.setText("Xóa");
        btn_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelActionPerformed(evt);
            }
        });

        btn_Add.setText("Thêm");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/Exit.png"))); // NOI18N
        btn_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OutActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã bảng lương ", "Mã nhân viên", "Số công", "Số giờ thiếu công", "Tổng lương"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        btn_Find.setText("Tìm kiếm");
        btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FindActionPerformed(evt);
            }
        });

        jLabel4.setText("Số công:");

        jLabel5.setText("Số giờ thiếu công:");

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_MaBL, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_GioThieuCong, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_SoCong, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Find)
                                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Del, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Out)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btn_Out))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Show)
                            .addComponent(btn_Add))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Del)
                            .addComponent(btn_Sua))
                        .addGap(18, 18, 18)
                        .addComponent(btn_Find))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_MaBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_SoCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_GioThieuCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowActionPerformed
            try {

            Connection kn=ketnoi.KNCSDL();

            String sql1="select * from tinhluong";

            Statement stm=kn.createStatement();

            ResultSet rs= stm.executeQuery(sql1);
            DefaultTableModel dtm=(DefaultTableModel)tb.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {
            Object objliss[] = {
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getInt(3) * 600000 + rs.getInt(4) * 60000
            };
            dtm.addRow(objliss);
            tb.setModel(dtm);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TinhLuong.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_ShowActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        int row= tb.getSelectedRow();

        String macc=tb.getValueAt(row, 0).toString();
        String manv=tb.getValueAt(row, 1).toString();
        String sc=tb.getValueAt(row, 2).toString();
        String tc=tb.getValueAt(row, 3).toString();
        
        txt_MaBL.setText(macc);
        txt_MaNV.setText(manv);
        txt_SoCong.setText(sc);
        txt_GioThieuCong.setText(tc);
 

 
    }//GEN-LAST:event_tbMouseClicked

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        String mabl= txt_MaBL.getText();
        String manv= txt_MaNV.getText();
        String sc= txt_SoCong.getText();
        String tc= txt_GioThieuCong.getText();
        int a=0;
        try {
            //Thêm dữ liệu vừa lấy được vào bảng csdl
            // Kết nối đến csdl
            Connection kn= ketnoi.KNCSDL(); 
            // Khai báo câu lệnh sql để thêm bản ghi vào csdl
            String sqlthem= "insert into tinhluong values ('"+mabl+"','"+manv+"','"+sc+"','"+tc+"','"+a+"')";
            // Khai báo đối tượng Statement để thực thi câu lẹnh sqlthem
            Statement stm = kn.createStatement();
            // Thực thi câu lệnh sqlthem
            stm.executeUpdate(sqlthem);
            //Cập nhật lại bảng trên form sau khi thêm
            //Khai báo câu lệnh sql sau khi lấy các bản ghi tring bảng sdl sau khi thêm
            String sql1="select * from tinhluong";
            // Thực thi câu lệnh sql trên và trả về các bản ghi
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm= (DefaultTableModel) tb.getModel();
            dtm.setRowCount(0);
            // Đọc rs và đưa lên bảng trên form 
           while (rs.next()) {
            Object objliss[] = {
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getInt(3) * 600000 + rs.getInt(4) * 60000
            };
                dtm.addRow(objliss);
                tb.setModel(dtm);
                

            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TinhLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FindActionPerformed
    String tuKhoa = txt_MaBL.getText().trim();
    

    if (tuKhoa.isEmpty()) {

        return;
    }


    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{"Mã bảng lương", "Mã nhân viên", "Số lương", "Số giờ thiếu công","Tổng lương"});
    

    DefaultTableModel currentModel = (DefaultTableModel) tb.getModel();
    for (int i = 0; i < currentModel.getRowCount(); i++) {

        String tenTrongBang = currentModel.getValueAt(i, 0).toString();

        if (tenTrongBang.equalsIgnoreCase(tuKhoa)) {
            model.addRow(new Object[]{
                currentModel.getValueAt(i, 0),
                currentModel.getValueAt(i, 1),
                currentModel.getValueAt(i, 2),
                currentModel.getValueAt(i, 3),
                currentModel.getValueAt(i, 4)
                
            });
        }
    }
    
    // Hiển thị kết quả tìm kiếm trên bảng tb
    tb.setModel(model);  
    }//GEN-LAST:event_btn_FindActionPerformed

    private void btn_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelActionPerformed
        String macanxoa = txt_MaBL.getText();
        try {
            Connection kn = ketnoi.KNCSDL();
            String sqlxoa= "delete from tinhluong where MaLuong ='"+macanxoa+"'";
            Statement stm = kn.createStatement();
            stm.executeUpdate(sqlxoa);
            int row= tb.getSelectedRow();
            DefaultTableModel dtm = (DefaultTableModel) tb.getModel();
            dtm.removeRow(row);
            
        
        } catch (SQLException ex) {
            Logger.getLogger(ChamCong.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_DelActionPerformed

    private void btn_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn thoát chứ","Thoát",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            dispose();
        }
        
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btn_OutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           
    }//GEN-LAST:event_formWindowOpened

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        String mabl= txt_MaBL.getText();
        String manv= txt_MaNV.getText();
        String sc= txt_SoCong.getText();
        String tc= txt_GioThieuCong.getText();
        int a=0;
        try {
        Connection kn = ketnoi.KNCSDL();
        String sqlsua = "UPDATE tinhluong SET MaNhanVien = '" + manv + "', TongCong = '" + sc + "', GioThieuCong = '" + tc + "', TongLuong = '" + a + "' WHERE MaLuong = '" + mabl + "'";

        Statement stm = kn.createStatement();

        int affectedRows = stm.executeUpdate(sqlsua);
        
        if (affectedRows > 0) {

            String sql1 = "SELECT * FROM tinhluong";
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm = (DefaultTableModel) tb.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {
                Object objliss[] = {
                    rs.getString(1), 
                    rs.getString(2), 
                    rs.getString(3),
                    rs.getString(4), 
                    rs.getInt(3) * 600000 + rs.getInt(4) * 60000
 
                };
                dtm.addRow(objliss);
            }
            tb.setModel(dtm);
        } else {

            System.out.println("Không tìm thấy bản ghi nào để sửa");
        }
        }
        catch (SQLException ex) {
            Logger.getLogger(ChamCong.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_SuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TinhLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Del;
    private javax.swing.JButton btn_Find;
    private javax.swing.JButton btn_Out;
    private javax.swing.JButton btn_Show;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txt_GioThieuCong;
    private javax.swing.JTextField txt_MaBL;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_SoCong;
    // End of variables declaration//GEN-END:variables
}
